### ISSUE TITLE
I'm having way too much fun with this

### ISSUE THREAD

**Issue by jonmagic** [fotoapp/fotoapp#13]
I spent pretty much my entire weekend hacking away on this, probably more time than I should have :grin: But dang it I'm having so much fun I don't want to stop.

@johndbritton I'd be interested to hear if you are still interested in hacking on something like this and how your vision for it differs from the few simple things I listed in the README.

I have been reviewing and merging my own PR's all weekend as this is just a fun project and rules would have slowed me down :grin: A lot of what I wrote may be utter shit, but I'm not really worried about it. I've just been iterating and having fun to see where it goes.

**Comment by johndbritton** [comment]
> I spent pretty much my entire weekend hacking away on this, probably more time than I should have :grin: But dang it I'm having so much fun I don't want to stop.

I love that feeling.

> @johndbritton I'd be interested to hear if you are still interested in hacking on something like this

Definitely.

> and how your vision for it differs from the few simple things I listed in the README.

I don't use iPhoto, or any other photo management software. I've been burned way too many times by proprietary library files and things like that.

The biggest thing for me is to make it simple to use. I'd love nothing more than to be able to set the clock on my camera and just drop every photo I take into this application. I don't want to have to manually add any data.

I like the idea of having a desktop uploader, right now I'm using a few custom scripts and Hazel to manage my collection of 15,000 or so photos. All I do is dump the photos from my camera into a directory and Hazel automatically organizes them into folders by date from the EXIF data.

**Comment by jonmagic** [comment]
Closing this as it isn't really actionable.
