### ISSUE TITLE
Desktop sync

### ISSUE THREAD

**Issue by jonmagic** [fotoapp/fotoapp#14]
I'm guessing the syncer will use md5sums and some sort of local database for checking what has been uploaded already.

The goal is to sync photos inside of `~/Pictures/iPhoto Library` and eventually be able to select other folders. What would be awesome is if the syncer had a simple plugin API so you could add syncers for iCloud, etc.

I care most about the iPhoto Library for now though so that is where I'm going to start.

**Comment by johndbritton** [comment]
How do you feel about the desktop sync client interacting with S3 directly? It might be a good way to simplify things.

Sync client uploads photos to S3, one photo at a time. At the end of a batch upload the sync client hits an API endpoint to trigger the app creating DB records for each photo in the bucket.

**Comment by johndbritton** [comment]
This could also be a security win. The webapp could have a separate IAM user that only has read permissions. That way users don't have to put keys that can write into the database.

**Comment by jonmagic** [comment]
Love the idea of having a read only IAM user for the web app, except that then you wouldn't be able to offer a web uploader at all? That might be a bummer.

**Comment by johndbritton** [comment]
You could have a read + write new objects but not edit.

**Comment by johndbritton** [comment]
My interest is around dealing with photos in bulk, so I don't think I'd ever use the web uploader.

**Comment by jonmagic** [comment]
Cool, same here. What time zone are you in right now? Any time for remote pair programming between Christmas and Jan 6th?

**Comment by johndbritton** [comment]
I'm in Taitung, Taiwan:

> johndbritton: you are in Chihshang Township, (Asia/Taipei), the time is 11:05am on Tue (+16 hours from HQ in San Francisco)

I'm pretty free and will probably be up late nights for the next few days. I'm definitely up for some pairing.

**Comment by jonmagic** [comment]
Looks like this has been started in https://github.com/fotoapp/uploader
