### ISSUE TITLE
Abandoning for now

### ISSUE THREAD

**Issue by jonmagic** [fotoapp/fotoapp#24]
Today I ran across https://picturelife.com and it meets 99% of my needs right now. It even gives an option to [bring your own S3 bucket](https://support.picturelife.com/hc/en-us/articles/202605823-Using-your-own-S3-bucket). I'm going to use their hosting for now though and just pay a flat monthly fee.

This means I probably won't continue working on fotoapp anytime soon. If I do it will be purely for doing analytics stuff, exploring things [like this](http://www.clarifai.com).

/cc @johndbritton

**Comment by johndbritton** [comment]
:+1: I'll give that a try too.
